name: Run-Import

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Run import
      env:
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_SERVER: ${{ secrets.DB_SERVER }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
      run: go run cmd/importer/*
